import Head from "next/head";
import { useProducts } from "../services/products";
import { Card } from "../components/card/Card";

export default function Home() {
  const { status, error, data } = useProducts();

  if (status === "loading") return <p>Cargando...</p>;

  console.log(data);
  return (
    <div>
      <Head>
        <title>Guitar Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {status === error ? (
        <p>{error?.message}</p>
      ) : (
        <main style={{ textAlign: "-webkit-center" }}>
          <h1 className="text-center text-blue-500 text-4xl font-bold">
            Guitar Store
          </h1>
          <section className="mt-10 m-auto">
            {data?.products.map((product, i) => (
              <div key={i}>
                <Card product={product} />
              </div>
            ))}
          </section>
        </main>
      )}
    </div>
  );
}
